import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
dotenv.config();

const supabase = createClient(
  process.env.VITE_SUPABASE_URL || '', 
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_SERVICE_ROLE_KEY || ''
);

async function run() {
  const mockNotif = {
    user_id: '47a00fbd-6e93-4b98-80e0-216be63870b2', 
    title: 'New Custom Alert',
    message: 'This is an automated test system alert generated by the test runner.',
    type: 'SYSTEM',
  };
  
  const { error: err1 } = await supabase.from('notifications').insert([mockNotif]);
  console.log('Notif Insert Error:', err1);

  const { data: notifData, error: err2 } = await supabase.from('notifications').select('*').eq('type', 'SYSTEM');
  console.log('Notif Fetch:', err2 || notifData?.[0]);
  
  await supabase.from('notifications').delete().eq('type', 'SYSTEM');
}
run();
