import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
dotenv.config();

const supabase = createClient(
  process.env.VITE_SUPABASE_URL || '', 
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_SERVICE_ROLE_KEY || ''
);

async function run() {
  console.log('--- 1. TESTING NOTIFICATIONS LOGIC ---');
  // Trigger a notification by creating a direct entry as if the system did it
  const mockNotif = {
    user_id: '47a00fbd-6e93-4b98-80e0-216be63870b2', 
    title: 'New Custom Alert',
    message: 'This is an automated test system alert generated by the test runner.',
    type: 'SYSTEM',
    read: false
  };
  
  await supabase.from('notifications').insert([mockNotif]);
  const { data: notifData } = await supabase.from('notifications').select('*').eq('type', 'SYSTEM').order('created_at', { ascending: false }).limit(1);
  console.log(notifData?.[0]);

  console.log('\n--- 2. TESTING DEDUP LOGIC DIRECTLY AGAINST AUDIT LOG ---');
  // First, verify our inserted signal from the last test is gone. We deleted it.
  // We'll insert a mock signal audit log
  const firstSignal = {
    pair: 'DEDUP_TEST',
    direction: 'SELL',
    tier: 'Elite',
    status: 'VALID',
    entry: 1.1504,
    sl: 1.1600,
    tp1: 1.1400
  };
  await supabase.from('signal_audit_log').insert([firstSignal]);
  
  // Now simulate the dedup logic inside scanner.ts
  const thirtyMinsAgo = new Date(Date.now() - 30 * 60 * 1000).toISOString();
  
  console.log('Querying Supabase for recently generated signals matching DEDUP_TEST SELL VALID...');
  const { data: dedupData } = await supabase
    .from('signal_audit_log')
    .select('entry')
    .eq('pair', 'DEDUP_TEST')
    .eq('direction', 'SELL')
    .eq('status', 'VALID')
    .gte('generated_at', thirtyMinsAgo);
    
  console.log('Found matching rows in time window:', dedupData);
  
  let isDuplicate = false;
  if (dedupData && dedupData.length > 0) {
     isDuplicate = dedupData.some(d => Math.abs((d.entry || 0) - 1.1504) < 0.00001);
  }
  
  console.log('Is this signal considered a duplicate by the logic? ->', isDuplicate);

  console.log('\n--- 3. CLEANUP ---');
  await supabase.from('notifications').delete().eq('type', 'SYSTEM');
  await supabase.from('signal_audit_log').delete().eq('pair', 'DEDUP_TEST');
}
run();
